-- SPDX-License-Identifier: Apache-2.0
-- Licensed to the Ed-Fi Alliance under one or more agreements.
-- The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
-- See the LICENSE and NOTICES files in the project root for more information.
-------------------------------------------------------------------------------
--01. AssessmentPerformanceLevel (data_assessments_5)
-------------------------------------------------------------------------------
INSERT INTO edfi.AssessmentPerformanceLevel (AssessmentIdentifier,AssessmentReportingMethodDescriptorId,Namespace,PerformanceLevelDescriptorId,MinimumScore,MaximumScore,ResultDatatypeTypeDescriptorId,CreateDate) VALUES ('01774fa3-06f1-47fe-8801-c8b1e65057f2',222,'uri://ed-fi.org/Assessment/Assessment.xml',1738,0,6,2066,GETDATE());
INSERT INTO edfi.AssessmentPerformanceLevel (AssessmentIdentifier,AssessmentReportingMethodDescriptorId,Namespace,PerformanceLevelDescriptorId,MinimumScore,MaximumScore,ResultDatatypeTypeDescriptorId,CreateDate) VALUES ('01774fa3-06f1-47fe-8801-c8b1e65057f2',222,'uri://ed-fi.org/Assessment/Assessment.xml',1737,7,7,2066,GETDATE());
INSERT INTO edfi.AssessmentPerformanceLevel (AssessmentIdentifier,AssessmentReportingMethodDescriptorId,Namespace,PerformanceLevelDescriptorId,MinimumScore,MaximumScore,ResultDatatypeTypeDescriptorId,CreateDate) VALUES ('01774fa3-06f1-47fe-8801-c8b1e65057f2',222,'uri://ed-fi.org/Assessment/Assessment.xml',1736,8,8,2066,GETDATE());
INSERT INTO edfi.AssessmentPerformanceLevel (AssessmentIdentifier,AssessmentReportingMethodDescriptorId,Namespace,PerformanceLevelDescriptorId,MinimumScore,MaximumScore,ResultDatatypeTypeDescriptorId,CreateDate) VALUES ('01774fa3-06f1-47fe-8801-c8b1e65057f2',222,'uri://ed-fi.org/Assessment/Assessment.xml',1739,9,10,2066,GETDATE());
INSERT INTO edfi.AssessmentPerformanceLevel (AssessmentIdentifier,AssessmentReportingMethodDescriptorId,Namespace,PerformanceLevelDescriptorId,MinimumScore,MaximumScore,ResultDatatypeTypeDescriptorId,CreateDate) VALUES ('19bcfe00-9c75-4d4f-ac2c-706e7479070f',222,'uri://ed-fi.org/Assessment/Assessment.xml',1738,0,6,2066,GETDATE());
INSERT INTO edfi.AssessmentPerformanceLevel (AssessmentIdentifier,AssessmentReportingMethodDescriptorId,Namespace,PerformanceLevelDescriptorId,MinimumScore,MaximumScore,ResultDatatypeTypeDescriptorId,CreateDate) VALUES ('19bcfe00-9c75-4d4f-ac2c-706e7479070f',222,'uri://ed-fi.org/Assessment/Assessment.xml',1737,7,7,2066,GETDATE());
INSERT INTO edfi.AssessmentPerformanceLevel (AssessmentIdentifier,AssessmentReportingMethodDescriptorId,Namespace,PerformanceLevelDescriptorId,MinimumScore,MaximumScore,ResultDatatypeTypeDescriptorId,CreateDate) VALUES ('19bcfe00-9c75-4d4f-ac2c-706e7479070f',222,'uri://ed-fi.org/Assessment/Assessment.xml',1736,8,8,2066,GETDATE());
INSERT INTO edfi.AssessmentPerformanceLevel (AssessmentIdentifier,AssessmentReportingMethodDescriptorId,Namespace,PerformanceLevelDescriptorId,MinimumScore,MaximumScore,ResultDatatypeTypeDescriptorId,CreateDate) VALUES ('19bcfe00-9c75-4d4f-ac2c-706e7479070f',222,'uri://ed-fi.org/Assessment/Assessment.xml',1739,9,10,2066,GETDATE());
INSERT INTO edfi.AssessmentPerformanceLevel (AssessmentIdentifier,AssessmentReportingMethodDescriptorId,Namespace,PerformanceLevelDescriptorId,MinimumScore,MaximumScore,ResultDatatypeTypeDescriptorId,CreateDate) VALUES ('1a6a5d20-4758-4f45-848d-59f3f03ae425',222,'uri://ed-fi.org/Assessment/Assessment.xml',1738,0,6,2066,GETDATE());
INSERT INTO edfi.AssessmentPerformanceLevel (AssessmentIdentifier,AssessmentReportingMethodDescriptorId,Namespace,PerformanceLevelDescriptorId,MinimumScore,MaximumScore,ResultDatatypeTypeDescriptorId,CreateDate) VALUES ('1a6a5d20-4758-4f45-848d-59f3f03ae425',222,'uri://ed-fi.org/Assessment/Assessment.xml',1737,7,7,2066,GETDATE());
INSERT INTO edfi.AssessmentPerformanceLevel (AssessmentIdentifier,AssessmentReportingMethodDescriptorId,Namespace,PerformanceLevelDescriptorId,MinimumScore,MaximumScore,ResultDatatypeTypeDescriptorId,CreateDate) VALUES ('1a6a5d20-4758-4f45-848d-59f3f03ae425',222,'uri://ed-fi.org/Assessment/Assessment.xml',1736,8,8,2066,GETDATE());
INSERT INTO edfi.AssessmentPerformanceLevel (AssessmentIdentifier,AssessmentReportingMethodDescriptorId,Namespace,PerformanceLevelDescriptorId,MinimumScore,MaximumScore,ResultDatatypeTypeDescriptorId,CreateDate) VALUES ('1a6a5d20-4758-4f45-848d-59f3f03ae425',222,'uri://ed-fi.org/Assessment/Assessment.xml',1739,9,10,2066,GETDATE());
INSERT INTO edfi.AssessmentPerformanceLevel (AssessmentIdentifier,AssessmentReportingMethodDescriptorId,Namespace,PerformanceLevelDescriptorId,MinimumScore,MaximumScore,ResultDatatypeTypeDescriptorId,CreateDate) VALUES ('39576404-04d2-4c06-a0e7-e2cb27968d01',222,'uri://ed-fi.org/Assessment/Assessment.xml',1738,0,6,2066,GETDATE());
INSERT INTO edfi.AssessmentPerformanceLevel (AssessmentIdentifier,AssessmentReportingMethodDescriptorId,Namespace,PerformanceLevelDescriptorId,MinimumScore,MaximumScore,ResultDatatypeTypeDescriptorId,CreateDate) VALUES ('39576404-04d2-4c06-a0e7-e2cb27968d01',222,'uri://ed-fi.org/Assessment/Assessment.xml',1737,7,7,2066,GETDATE());
INSERT INTO edfi.AssessmentPerformanceLevel (AssessmentIdentifier,AssessmentReportingMethodDescriptorId,Namespace,PerformanceLevelDescriptorId,MinimumScore,MaximumScore,ResultDatatypeTypeDescriptorId,CreateDate) VALUES ('39576404-04d2-4c06-a0e7-e2cb27968d01',222,'uri://ed-fi.org/Assessment/Assessment.xml',1736,8,8,2066,GETDATE());
INSERT INTO edfi.AssessmentPerformanceLevel (AssessmentIdentifier,AssessmentReportingMethodDescriptorId,Namespace,PerformanceLevelDescriptorId,MinimumScore,MaximumScore,ResultDatatypeTypeDescriptorId,CreateDate) VALUES ('39576404-04d2-4c06-a0e7-e2cb27968d01',222,'uri://ed-fi.org/Assessment/Assessment.xml',1739,9,10,2066,GETDATE());
INSERT INTO edfi.AssessmentPerformanceLevel (AssessmentIdentifier,AssessmentReportingMethodDescriptorId,Namespace,PerformanceLevelDescriptorId,MinimumScore,MaximumScore,ResultDatatypeTypeDescriptorId,CreateDate) VALUES ('3e0e2cac-847b-4ddd-93ec-925826552447',222,'uri://ed-fi.org/Assessment/Assessment.xml',1738,0,6,2066,GETDATE());
INSERT INTO edfi.AssessmentPerformanceLevel (AssessmentIdentifier,AssessmentReportingMethodDescriptorId,Namespace,PerformanceLevelDescriptorId,MinimumScore,MaximumScore,ResultDatatypeTypeDescriptorId,CreateDate) VALUES ('3e0e2cac-847b-4ddd-93ec-925826552447',222,'uri://ed-fi.org/Assessment/Assessment.xml',1737,7,7,2066,GETDATE());
INSERT INTO edfi.AssessmentPerformanceLevel (AssessmentIdentifier,AssessmentReportingMethodDescriptorId,Namespace,PerformanceLevelDescriptorId,MinimumScore,MaximumScore,ResultDatatypeTypeDescriptorId,CreateDate) VALUES ('3e0e2cac-847b-4ddd-93ec-925826552447',222,'uri://ed-fi.org/Assessment/Assessment.xml',1736,8,8,2066,GETDATE());
INSERT INTO edfi.AssessmentPerformanceLevel (AssessmentIdentifier,AssessmentReportingMethodDescriptorId,Namespace,PerformanceLevelDescriptorId,MinimumScore,MaximumScore,ResultDatatypeTypeDescriptorId,CreateDate) VALUES ('3e0e2cac-847b-4ddd-93ec-925826552447',222,'uri://ed-fi.org/Assessment/Assessment.xml',1739,9,10,2066,GETDATE());
INSERT INTO edfi.AssessmentPerformanceLevel (AssessmentIdentifier,AssessmentReportingMethodDescriptorId,Namespace,PerformanceLevelDescriptorId,MinimumScore,MaximumScore,ResultDatatypeTypeDescriptorId,CreateDate) VALUES ('97e16cba-5fb0-438b-be0e-7f7fb6b591dc',222,'uri://ed-fi.org/Assessment/Assessment.xml',1738,0,6,2066,GETDATE());
INSERT INTO edfi.AssessmentPerformanceLevel (AssessmentIdentifier,AssessmentReportingMethodDescriptorId,Namespace,PerformanceLevelDescriptorId,MinimumScore,MaximumScore,ResultDatatypeTypeDescriptorId,CreateDate) VALUES ('97e16cba-5fb0-438b-be0e-7f7fb6b591dc',222,'uri://ed-fi.org/Assessment/Assessment.xml',1737,7,7,2066,GETDATE());
INSERT INTO edfi.AssessmentPerformanceLevel (AssessmentIdentifier,AssessmentReportingMethodDescriptorId,Namespace,PerformanceLevelDescriptorId,MinimumScore,MaximumScore,ResultDatatypeTypeDescriptorId,CreateDate) VALUES ('97e16cba-5fb0-438b-be0e-7f7fb6b591dc',222,'uri://ed-fi.org/Assessment/Assessment.xml',1736,8,8,2066,GETDATE());
INSERT INTO edfi.AssessmentPerformanceLevel (AssessmentIdentifier,AssessmentReportingMethodDescriptorId,Namespace,PerformanceLevelDescriptorId,MinimumScore,MaximumScore,ResultDatatypeTypeDescriptorId,CreateDate) VALUES ('97e16cba-5fb0-438b-be0e-7f7fb6b591dc',222,'uri://ed-fi.org/Assessment/Assessment.xml',1739,9,10,2066,GETDATE());
INSERT INTO edfi.AssessmentPerformanceLevel (AssessmentIdentifier,AssessmentReportingMethodDescriptorId,Namespace,PerformanceLevelDescriptorId,MinimumScore,MaximumScore,ResultDatatypeTypeDescriptorId,CreateDate) VALUES ('ae049cb3-33d0-431f-b0f3-a751df7217ef',222,'uri://ed-fi.org/Assessment/Assessment.xml',1738,0,6,2066,GETDATE());
INSERT INTO edfi.AssessmentPerformanceLevel (AssessmentIdentifier,AssessmentReportingMethodDescriptorId,Namespace,PerformanceLevelDescriptorId,MinimumScore,MaximumScore,ResultDatatypeTypeDescriptorId,CreateDate) VALUES ('ae049cb3-33d0-431f-b0f3-a751df7217ef',222,'uri://ed-fi.org/Assessment/Assessment.xml',1737,7,7,2066,GETDATE());
INSERT INTO edfi.AssessmentPerformanceLevel (AssessmentIdentifier,AssessmentReportingMethodDescriptorId,Namespace,PerformanceLevelDescriptorId,MinimumScore,MaximumScore,ResultDatatypeTypeDescriptorId,CreateDate) VALUES ('ae049cb3-33d0-431f-b0f3-a751df7217ef',222,'uri://ed-fi.org/Assessment/Assessment.xml',1736,8,8,2066,GETDATE());
INSERT INTO edfi.AssessmentPerformanceLevel (AssessmentIdentifier,AssessmentReportingMethodDescriptorId,Namespace,PerformanceLevelDescriptorId,MinimumScore,MaximumScore,ResultDatatypeTypeDescriptorId,CreateDate) VALUES ('ae049cb3-33d0-431f-b0f3-a751df7217ef',222,'uri://ed-fi.org/Assessment/Assessment.xml',1739,9,10,2066,GETDATE());
INSERT INTO edfi.AssessmentPerformanceLevel (AssessmentIdentifier,AssessmentReportingMethodDescriptorId,Namespace,PerformanceLevelDescriptorId,MinimumScore,MaximumScore,ResultDatatypeTypeDescriptorId,CreateDate) VALUES ('d128cfa6-b3df-430c-b671-c76d9822417d',222,'uri://ed-fi.org/Assessment/Assessment.xml',1738,0,6,2066,GETDATE());
INSERT INTO edfi.AssessmentPerformanceLevel (AssessmentIdentifier,AssessmentReportingMethodDescriptorId,Namespace,PerformanceLevelDescriptorId,MinimumScore,MaximumScore,ResultDatatypeTypeDescriptorId,CreateDate) VALUES ('d128cfa6-b3df-430c-b671-c76d9822417d',222,'uri://ed-fi.org/Assessment/Assessment.xml',1737,7,7,2066,GETDATE());
INSERT INTO edfi.AssessmentPerformanceLevel (AssessmentIdentifier,AssessmentReportingMethodDescriptorId,Namespace,PerformanceLevelDescriptorId,MinimumScore,MaximumScore,ResultDatatypeTypeDescriptorId,CreateDate) VALUES ('d128cfa6-b3df-430c-b671-c76d9822417d',222,'uri://ed-fi.org/Assessment/Assessment.xml',1736,8,8,2066,GETDATE());
INSERT INTO edfi.AssessmentPerformanceLevel (AssessmentIdentifier,AssessmentReportingMethodDescriptorId,Namespace,PerformanceLevelDescriptorId,MinimumScore,MaximumScore,ResultDatatypeTypeDescriptorId,CreateDate) VALUES ('d128cfa6-b3df-430c-b671-c76d9822417d',222,'uri://ed-fi.org/Assessment/Assessment.xml',1739,9,10,2066,GETDATE());
INSERT INTO edfi.AssessmentPerformanceLevel (AssessmentIdentifier,AssessmentReportingMethodDescriptorId,Namespace,PerformanceLevelDescriptorId,MinimumScore,MaximumScore,ResultDatatypeTypeDescriptorId,CreateDate) VALUES ('f3115910-9d0d-451c-b94f-e617657660f9',222,'uri://ed-fi.org/Assessment/Assessment.xml',1738,0,6,2066,GETDATE());
INSERT INTO edfi.AssessmentPerformanceLevel (AssessmentIdentifier,AssessmentReportingMethodDescriptorId,Namespace,PerformanceLevelDescriptorId,MinimumScore,MaximumScore,ResultDatatypeTypeDescriptorId,CreateDate) VALUES ('f3115910-9d0d-451c-b94f-e617657660f9',222,'uri://ed-fi.org/Assessment/Assessment.xml',1737,7,7,2066,GETDATE());
INSERT INTO edfi.AssessmentPerformanceLevel (AssessmentIdentifier,AssessmentReportingMethodDescriptorId,Namespace,PerformanceLevelDescriptorId,MinimumScore,MaximumScore,ResultDatatypeTypeDescriptorId,CreateDate) VALUES ('f3115910-9d0d-451c-b94f-e617657660f9',222,'uri://ed-fi.org/Assessment/Assessment.xml',1736,8,8,2066,GETDATE());
INSERT INTO edfi.AssessmentPerformanceLevel (AssessmentIdentifier,AssessmentReportingMethodDescriptorId,Namespace,PerformanceLevelDescriptorId,MinimumScore,MaximumScore,ResultDatatypeTypeDescriptorId,CreateDate) VALUES ('f3115910-9d0d-451c-b94f-e617657660f9',222,'uri://ed-fi.org/Assessment/Assessment.xml',1739,9,10,2066,GETDATE());
INSERT INTO edfi.AssessmentPerformanceLevel (AssessmentIdentifier,AssessmentReportingMethodDescriptorId,Namespace,PerformanceLevelDescriptorId,MinimumScore,MaximumScore,ResultDatatypeTypeDescriptorId,CreateDate) VALUES ('f4863c33-6df0-41eb-9501-5ef2e46216c3',222,'uri://ed-fi.org/Assessment/Assessment.xml',1738,0,6,2066,GETDATE());
INSERT INTO edfi.AssessmentPerformanceLevel (AssessmentIdentifier,AssessmentReportingMethodDescriptorId,Namespace,PerformanceLevelDescriptorId,MinimumScore,MaximumScore,ResultDatatypeTypeDescriptorId,CreateDate) VALUES ('f4863c33-6df0-41eb-9501-5ef2e46216c3',222,'uri://ed-fi.org/Assessment/Assessment.xml',1737,7,7,2066,GETDATE());
INSERT INTO edfi.AssessmentPerformanceLevel (AssessmentIdentifier,AssessmentReportingMethodDescriptorId,Namespace,PerformanceLevelDescriptorId,MinimumScore,MaximumScore,ResultDatatypeTypeDescriptorId,CreateDate) VALUES ('f4863c33-6df0-41eb-9501-5ef2e46216c3',222,'uri://ed-fi.org/Assessment/Assessment.xml',1736,8,8,2066,GETDATE());
INSERT INTO edfi.AssessmentPerformanceLevel (AssessmentIdentifier,AssessmentReportingMethodDescriptorId,Namespace,PerformanceLevelDescriptorId,MinimumScore,MaximumScore,ResultDatatypeTypeDescriptorId,CreateDate) VALUES ('f4863c33-6df0-41eb-9501-5ef2e46216c3',222,'uri://ed-fi.org/Assessment/Assessment.xml',1739,9,10,2066,GETDATE());
-- SAT
INSERT INTO edfi.AssessmentPerformanceLevel (AssessmentIdentifier,AssessmentReportingMethodDescriptorId,Namespace,PerformanceLevelDescriptorId,MinimumScore,MaximumScore,ResultDatatypeTypeDescriptorId,CreateDate) VALUES ('SAT Writing',222,'uri://ed-fi.org/Assessment/Assessment.xml',1738, 0,4,2066, GETDATE());
INSERT INTO edfi.AssessmentPerformanceLevel (AssessmentIdentifier,AssessmentReportingMethodDescriptorId,Namespace,PerformanceLevelDescriptorId,MinimumScore,MaximumScore,ResultDatatypeTypeDescriptorId,CreateDate) VALUES ('SAT Critical Reading',222,'uri://ed-fi.org/Assessment/Assessment.xml',1738, 0,479,2066, GETDATE());
INSERT INTO edfi.AssessmentPerformanceLevel (AssessmentIdentifier,AssessmentReportingMethodDescriptorId,Namespace,PerformanceLevelDescriptorId,MinimumScore,MaximumScore,ResultDatatypeTypeDescriptorId,CreateDate) VALUES ('SAT Mathematics',222,'uri://ed-fi.org/Assessment/Assessment.xml',1738, 0,529,2066, GETDATE());